dbsales:
  outputs:
    dev:
      dbname: '{{ env_var(''DB_NAME_PROD'') }}'
      host: '{{ env_var(''DB_HOST_PROD'') }}'
      keepalives_idle: 0
      password: '{{ env_var(''DB_PASS_PROD'') }}'
      port: '{{ env_var(''DB_PORT_PROD'') | int }}'
      schema: '{{ env_var(''DB_SCHEMA_PROD'') }}'
      threads: '{{ env_var(''DB_THREADS_PROD'') | int }}'
      type: postgres
      user: '{{ env_var(''DB_USER_PROD'') }}'
  target: dev
